### ISSUE TITLE
Can it run doom yet?

### ISSUE THREAD

**Issue by orhun** [cxreiff/bevy_ratatui_camera#1]
https://canitrundoom.org/

**Comment by cxreiff** [comment]
I actually did glance around to see if someone had cloned Doom in Bevy so I could try it out 😆. There is [patryk27/doome](https://github.com/patryk27/doome), but its not *quite* doom.

**Comment by Chleba** [comment]
I was thinking the same thing :+1:

**Comment by orhun** [comment]
<https://github.com/cryptocode/terminal-doom>
